# Generated by Django 2.1.7 on 2019-02-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trade',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='tsb.Trade'),
            preserve_default=False,
        ),
    ]
